### ISSUE TITLE
Install Error (File "/tmp/pip-install-e_zcg5qo/python-rrdtool/setup.py", line 61         os.chmod(executable, 0777))

### ISSUE THREAD

**Issue by gato-gto** [okami-1/django-rrd#3]
**Issuse**
install [python-rrdtool](https://github.com/alertedsnake/python-rrdtool)
```
(env) machine@user:~/project$ pip install python-rrdtool
Collecting python-rrdtool
  Using cached python-rrdtool-1.4.7.tar.gz (1.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/machine/project/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e_zcg5qo/python-rrdtool/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e_zcg5qo/python-rrdtool/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-e_zcg5qo/python-rrdtool/pip-egg-info
         cwd: /tmp/pip-install-e_zcg5qo/python-rrdtool/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e_zcg5qo/python-rrdtool/setup.py", line 61
        os.chmod(executable, 0777)
                                ^
    SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```(env) machine@user:~/project$ pip install python-rrdtool
Collecting python-rrdtool
  Using cached python-rrdtool-1.4.7.tar.gz (1.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/machine/project/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e_zcg5qo/python-rrdtool/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e_zcg5qo/python-rrdtool/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-e_zcg5qo/python-rrdtool/pip-egg-info
         cwd: /tmp/pip-install-e_zcg5qo/python-rrdtool/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e_zcg5qo/python-rrdtool/setup.py", line 61
        os.chmod(executable, 0777)
                                ^
    SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
**Fix**
```
os.chmod(executable, stat.S_IRWXU|stat.S_IRWXG|stat.S_IRWXO)
```

**Comment by gato-gto** [comment]
[python-rrdtool](https://github.com/alertedsnake/python-rrdtool)

**Comment by gato-gto** [comment]
`os.chmod(executable, stat.S_IRWXU|stat.S_IRWXG|stat.S_IRWXO)`
